### ISSUE TITLE
More modular code

### ISSUE THREAD

**Issue by andrewguilas** [Vex87/Velocity-Admin#1]

**Comment by andrewguilas** [comment]
Changed status from "To Do" to "In Progress"

**Comment by advanceinnovations** [comment]
owo

**Comment by Liam31** [comment]
STOP DELETING 😡

**Comment by andrewguilas** [comment]
Continue to make code more modular to prepare for argument parsing.

**Comment by andrewguilas** [comment]
Closed in 13de39c3ce4de76fbbb44bfe6033f9f85e74e0fe

**Comment by andrewguilas** [comment]
Changed status from "In Progress" to "Completed"
