### ISSUE TITLE
Organize code

### ISSUE THREAD

**Issue by andrewguilas** [Vex87/Velocity-Admin#11]

**Comment by andrewguilas** [comment]
Make separate modules for input and autocomplete.

**Comment by andrewguilas** [comment]
Use “do” operator when setting properties of created instances.

**Comment by andrewguilas** [comment]
Changed status from "In Progress" to "Completed"

**Comment by Liam31** [comment]
hi

**Comment by Liam31** [comment]
👀

**Comment by andrewguilas** [comment]
> 👀

coner ti bellamao ni advanceinnovations sagura uney

**Comment by Liam31** [comment]
i dont speak mexican

**Comment by andrewguilas** [comment]
> i dont speak mexican

bro it’s actually american

go to math school
